byecorona/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('main.urls', namespace='home')),
    path('', include('infographic.urls', namespace='infografis')),
    path('news/', include('news.urls', namespace='news')),
    path('preventions/', include('preventions.urls', namespace='preventions')),
    path('peta/', include('peta.urls', namespace='peta')),
    path('signup/', include('signup.urls', namespace='signup')),
    path('login/', include('login.urls', namespace='login'))
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('savedata/', views.savedata, name='savedata'),
]

preventions/urls.py
from django.urls import path

from . import views

app_name = 'preventions'

urlpatterns = [
    path('', views.preventions, name='preventions'),
    path('data/', views.data, name='data'),
]

preventions/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    name = models.CharField(max_length=15)
    message = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_dict(self):
        return {
            'name' : self.name,
            'message' : self.message,
        }

preventions/forms.py
from django.forms import ModelForm
from django import forms
from .models import Message

class MessageForm(forms.ModelForm):
	class Meta:
		model = Message
		fields = (
		    'message',
		)

		widgets = {
			'message': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter Your Message'}),
		}

preventions/views.py
from django.shortcuts import render, redirect
from .models import Message
from .forms import MessageForm
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
import requests
import json

def preventions(request):
    responses = {}
    if request.method == 'POST':
        if request.is_ajax():
            if request.user.is_authenticated:
                form = MessageForm(request.POST)
                if form.is_valid():
                    name = request.user.username
                    message = form.cleaned_data['message']
                    Message(name=name, message = message).save()
                    return JsonResponse({'success': True})
        return JsonResponse({'success': False})

    else:
        form = MessageForm()
        responses['form'] = form
        return render(request, 'preventions/preventions.html', responses)

def data(request):
    data = {
        'data' : [i.get_dict() for i in Message.objects.all()[::-1][:]],
    }
    return JsonResponse(data=data)

preventions/templates/preventions/preventions.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Header -->
<div class="container-fluid header">
    <div class="row content">
        <div class="col-sm-6 word text-center">
            <br><br>
            <h1 class="first"><b>How to Prevent?</b></h1>
        </div>
        <div class="col-sm-6 image text-center">
            <img class="imageviruspreventions" src="{% static 'img/virus.png' %}">
        </div>
    </div>
</div>
<!-- Isi -->
<div class="container-fluid isi text-center">
    <!-- What to Do Section -->
    <div class="row">
        <h3 class="margin statjudul text-center">What to Do?</h3><br>  
        <div class="col-sm-7">
            <div class="col-sm-4">
                <img class = "myimg" src="{% static 'img/wash_your_hand.png' %}">
                <p class="stat">Wash Your Hand</p>
            </div>
            <div class="col-sm-4"> 
                <img class = "myimg" src="{% static 'img/wear_facemask.png' %}">
                <p class="stat">Wear Facemask</p>
            </div>
            <div class="col-sm-4"> 
                <img class = "myimg" src="{% static 'img/stay_at_home.png' %}">
                <p class="stat">Stay at Home</p>
            </div>
        </div>
        <div class="col-sm-5">
            <div class="col-sm-6"> 
                <img class = "myimg" src="{% static 'img/social_distancing.png' %}">
                <p class="stat">Social Distancing</p>
            </div>
            <div class="col-sm-6"> 
                <img class = "myimg" src="{% static 'img/call_if_you.png' %}">
                <p class="stat">Call If You???</p>
            </div>
        </div>
    </div>
    <!-- Know Your Symtomps Section -->
    <div class="row" style=margin-bottom:8%>
        <h3 class="margin statjudul">Know Your Symtomps</h3><br>
        <div class="col-sm-3">
            <img class = "myimg" src="{% static 'img/38_C.png' %}">
            <p class="stat">> 38°C</p>
        </div>
        <div class="col-sm-3"> 
            <img class = "myimg" src="{% static 'img/dry_cough.png' %}">
            <p class="stat">Dry Cough</p>
        </div>
        <div class="col-sm-3"> 
            <img class = "myimg" src="{% static 'img/tiredness.png' %}">
             <p class="stat">Tiredness</p>
        </div>
        <div class="col-sm-3"> 
            <img class = "myimg" src="{% static 'img/trouble_breathing.png' %}">
            <p class="stat">Trouble Breathing</p>
        </div>
    </div>
    <!-- Share Tips with Others to Fight Covid-19 -->
    <div id="share-tips" class="row form-p1">
        <h3 class="margin statjudul">Share Tips with Others to Fight Covid-19</h3>
        <br><br>
        <div class="col-sm-6">
            <div class="form-p">
            </div>
        </div>
        <div class="col-sm-6"> 
            {% if user.is_authenticated %}
            <div class="form-group form-p2 text-left">
                <form method="POST" id="formmessage">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Submit" class="btn btn-outline-dark btn-blue" id="submitform">
                </form>
            </div>
            {% else %}
            <h3 class="stat">Login first <a href="/login/">here</a> before you share tips!</h3> <br><br>
            {% endif %}
        </div>
    </div>
</div>

<script>
    var url = '{% url "preventions:data" %}'
    var url2 = '{% url "preventions:preventions" %}'
</script>
<script src="{% static 'preventions/preventions.js' %}"></script>
{% endblock content %}