byecorona/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('main.urls', namespace='home')),
    path('', include('infographic.urls', namespace='infografis')),
    path('news/', include('news.urls', namespace='news')),
    path('preventions/', include('preventions.urls', namespace='preventions')),
    path('peta/', include('peta.urls', namespace='peta')),
    path('signup/', include('signup.urls', namespace='signup')),
    path('login/', include('login.urls', namespace='login'))
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('savedata/', views.savedata, name='savedata'),
]

peta/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.feedback, name='feedback'),
    path('fungsi_data/', views.fungsi_data, name='fungsi_data'),
]

peta/models.py
from django.db import models

# Create your models here.
class Feedback(models.Model):
    name = models.CharField(max_length=200)
    feedback = models.CharField(max_length=200)

    def get_dict(self):
        return {
            'name':self.name,
            'feedback':self.feedback
        }

peta/forms.py
from django.forms import ModelForm
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
	class Meta:
		model = Feedback
		fields = (
		    'feedback',
		)

		widgets = {
			'feedback': forms.Textarea(attrs={'class': 'form-control'}),
		}

peta/views.py
from django.shortcuts import render, redirect
from .models import Feedback
from .forms import FeedbackForm
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
import requests
import json


def feedback(request):
    responses = {}
    if request.method == 'POST':
        if request.is_ajax():
            if request.user.is_authenticated:
                form = FeedbackForm(request.POST)
                if form.is_valid():
                    name = request.user.username
                    feedback = form.cleaned_data['feedback']
                    Feedback(name=name, feedback=feedback).save()
                    return JsonResponse({'success': True})
        return JsonResponse({'success': False})

    else:
        form = FeedbackForm()
        responses['form'] = form
        return render(request, 'peta/peta.html', responses)

def fungsi_data(request):
    data = {
        'data':[i.get_dict() for i in Feedback.objects.all()[::-1][:5]],
    }
    return JsonResponse(data=data)

peta/templates/peta/peta.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Header -->
<div class="container-fluid header">
    <div class="row content">
        <div class="col-sm-6 word text-center">
            <h1 class="first"><b>Where Do You</b></h1>
            <h1 class="second"><b>Have To Go?</b></h1>
        </div>
        <div class="col-sm-6 image text-center">
            <img class="imagemap" src="{% static 'img/map.png' %}">
        </div>
    </div>
</div>
<!-- Isi -->
<script src="https://kit.fontawesome.com/a076d05399.js"></script>


        <div class="map text-center">
            <iframe width="100%" height="400" src="https://www.google.com/maps/d/embed?mid=1G0xfB8QRIFsLkZHLCHVX4faL7RxDLPdG" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
  
        <div class="container isi">
            <h2 class="hotlines"><b>HOTLINES</b></h2>
        </div>
        <div class="container-fluid isi">
            <div class="row content">
                <div class="col-sm-6 text-center">
                    
                    <h5>RSU Dr. Zainoel Abidin Banda Aceh 081287370956</h5>
                    <h5>RSU H. Adam Malik Medan 081287370956</h5>
                    <h5>RSU Dr. M. Jamil Padang 081287370956</h5>
                    <h5>RSU Arifin Ahmad Pekan Baru 081287370956</h5>
                    <h5>RS Otorita Batam 081287370956</h5>
                    <h5>RSU Raden Mattaher Jambi 081287370956</h5>
                    <h5>RSU Dr. M. Hoesin Palembang 081287370956</h5>
                    <h5>RSU Tanjung Pandan 081287370956</h5>
                </div>
                <div class="col-sm-6 text-center">
                    <h5>RSU Dr. M. Yunus Bengkulu 081287370956</h5>
                    <h5>RSU Abdul Moeloek 081287370956</h5>
                    <h5>RSPI Dr. Sulianti Saroso  081287370956</h5>
                    <h5>RSU Dr. Hasan Sadikin Bandung 081287370956</h5>
                    <h5>RSU Serang 081287370956</h5>
                    <h5>RSU Dr. Kariadi Semarang 081287370956</h5>
                    <h5>RSU Dr. Sardjito 081287370956</h5>
                    <br>
                    <br>
                    <br>
                    <br>
                </div>

            </div>

            <div class="row content">
                <div class="container-fluid headermap">
                        <h2 class="hotlines"><b>FEEDBACK</b></h2>
                <div class="col-lg-6" style="float:none;margin:auto;">
                    {% if user.is_authenticated %}
                <form method="POST" id="formfeedback">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input id="submitan" type="submit" value="Submit" class="btn btn-outline-dark btn-blue">
                </form>
                    {% else %}
                    <h1 style="text-align: center;">Login dulu!</h1>
                    {% endif %}
                <br>
                <br>
                </div>

                <div id="feedback-result">
                        <br>
                    <!-- json -->
                </div>
                
            </div>
            </div>



<script>
var url = '{% url "peta:fungsi_data" %}'
var url2 = '{% url "peta:feedback" %}'
</script>

<script src="{% static 'img/peta.js' %}"></script>

</div>
{% endblock content %}